# Fichier : k8s/kustomization.yml
# Fichier de kustomization pour le d√©ploiement de l'application

resources:
  - secrets.yml
  - db-deployment.yml
  - pgadmin-deployment.yml
  - backend-deployment.yml
  - frontend-deployment.yml
