# Fichier : k8s/secrets.yml
# Déclaration des secrets pour la base de données et pgAdmin

# Secret pour la base de données PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  # Les valeurs sont encodées en base64
  # POSTGRES_DB: postgres
  POSTGRES_DB: cG9zdGdyZXM=
  # POSTGRES_USER: admin
  POSTGRES_USER: YWRtaW4=
  # POSTGRES_PASSWORD: admin123
  POSTGRES_PASSWORD: YWRtaW4xMjM=

---

# Secret pour pgAdmin
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
type: Opaque
data:
  # Les valeurs sont encodées en base64
  # PGADMIN_DEFAULT_EMAIL: admin@gmail.com
  PGADMIN_DEFAULT_EMAIL: YWRtaW5AZ21haWwuY29t
  # PGADMIN_DEFAULT_PASSWORD: admin1234
  PGADMIN_DEFAULT_PASSWORD: YWRtaW4xMjM0
